formatter: "markdown"

version: ""

header-from: header.md
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: ["modules"]
  show: []

content: ""

output:
  file: "README.md"
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true